### ISSUE TITLE
Porting the package to JuliaPhysics

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPhysics/ThinFilmsTools.jl#39]
Hi @carstenbauer !

I'm reaching out to you and the JuliaPhysics team to see if you would like to port the [ThinFilmsTools.jl](https://github.com/lnacquaroli/ThinFilmsTools.jl) package into JuliaPhysics. I don't know what are the requirements to get there, but I thought it could be useful to port it and have more exposure and extend the package capabilities if desired. I've written this module years ago but I don't have much time right now to dedicate to it either. However, I'm willing to discuss any comments and implementation ideas. 

For the explanation of the package please check the [Wiki](https://github.com/lnacquaroli/ThinFilmsTools.jl/wiki) pages.

Thanks! Best,

Leandro.

BTW, I just registered the package.

**Comment by lnacquaroli** [comment]
Hi @roflmaostc, reaching out again before closing this issue. See above.

**Comment by roflmaostc** [comment]
Should I move it?

I can check whether I've got the permissions

**Comment by lnacquaroli** [comment]
Yes, go ahead. Let me know...

**Comment by roflmaostc** [comment]
Not quite sure, but can you add me to this repo here such that I have permissions to move it? (probably as Admin?)

**Comment by lnacquaroli** [comment]
I just added you as a collaborator, not sure if that is enough...

**Comment by roflmaostc** [comment]
Thanks, I think the permissions are not enough :/

**Comment by lnacquaroli** [comment]
I might need to transfer the repository to another username or organization. Is JuliaPhysics an organization type?

**Comment by roflmaostc** [comment]
I think you need to give me admin rights, I can move it to JuliaPhysics then

**Comment by lnacquaroli** [comment]
I don't see the option to give you admin access to the repo. I will try to transfer the package to the JuliaPhysics org if you are OK with it.

**Comment by roflmaostc** [comment]
Does that work? 
Ah, didn't know it! But go for it

**Comment by roflmaostc** [comment]
Hi @giordano,

can you add @lnacquaroli to the JuliaPhysics org?

**Comment by lnacquaroli** [comment]
Done, thanks!
